pipedir = /TBI/Share/BioPeople/siyoo/BioTools/pipeline_cookiecutter
params = /TBI/Share/BioPeople/siyoo/BioTools/pipeline_cookiecutter/config/params.yaml
workdir = /Users/seung1yoo/git/pipeline_cookiecutter/test

samples:
  A:
    bam: /Users/seung1yoo/git/pipeline_cookiecutter/test/input/sample_1.bam
  B:
    bam: /Users/seung1yoo/git/pipeline_cookiecutter/test/input/sample_2.bam
